services:
  db:
    image: postgres:15
    container_name: sop_db_container
    restart: always
    environment:
      POSTGRES_DB: desafio_sop_db
      POSTGRES_USER: sopdba
      POSTGRES_PASSWORD: sop123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d


volumes:
  postgres_data: