app:
  frontend:
    url: https://gestao-orcamento-sop-frontend-4wgl97iw9.vercel.app/
    
server:
  port: ${PORT:10230}

spring:
  threads:
    virtual:
      enabled: true

  datasource:
    url: "jdbc:postgresql://centerbeam.proxy.rlwy.net:42918/postgres"
    username: postgres
    password: sClCRqfdSQYxFduFNasvEHHqXILXgYSY
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: controle_obras
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha

api:
  security:
    token:
      secret: ${API_SECURITY_TOKEN_SECRET}/
