app:
  frontend:
    url: https://gestao-orcamento-sop-frontend-1a4n1i5gd.vercel.app/
    
server:
  port: ${PORT:10230}

spring:
  threads:
    virtual:
      enabled: true

  datasource:
    url: "jdbc:postgresql://dpg-d6cc59vpm1nc73ch99f0-a.ohio-postgres.render.com:5432/desafio_sop_db"
    username: sopdba
    password: HLjNttSfo2z0WTv6PqtlKsgqb8PLUTZL
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: controle_obras
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha

api:
  security:
    token:
      secret: ${API_SECURITY_TOKEN_SECRET}/
